// Regenerate docs/football/CONCEPTS.md from the data (the data is the source of truth):
//   node tools/concepts-doc.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import vm from 'node:vm';

const root = new URL('../', import.meta.url);
const text = (p) => readFileSync(new URL(p, root), 'utf8');
const read = (p) => JSON.parse(text(p));
const ctx = { console };
ctx.window = ctx;
vm.createContext(ctx);
vm.runInContext(text('src/data/concepts.js'), ctx);

const manifest = read('src/data/manifest.json');
const forms = Object.fromEntries(manifest.formations.map((f) => { const j = read(`src/data/${f}`); return [j.id, j]; }));
const plays = [];
for (const c of manifest.concepts || []) plays.push(...ctx.FD.Concepts.expand(read(`src/data/${c}`), forms).plays);
for (const p of manifest.plays) plays.push(read(`src/data/${p}`));

// One entry per concept; presentations listed together.
const byConcept = new Map();
for (const p of plays) {
  if (!byConcept.has(p.conceptId)) byConcept.set(p.conceptId, []);
  byConcept.get(p.conceptId).push(p);
}
const ORDER = ['dropback_pass', 'quick_pass', 'play_action', 'rpo', 'screen', 'run'];
const LABEL = { dropback_pass: 'Dropback pass', quick_pass: 'Quick game', play_action: 'Play-action', rpo: 'RPO', screen: 'Screens', run: 'Run game' };
const groups = Array.from(byConcept.values()).sort((a, b) =>
  ORDER.indexOf(a[0].family) - ORDER.indexOf(b[0].family) || a[0].name.localeCompare(b[0].name));

let md = `# Football concept reference

Generated by \`node tools/concepts-doc.mjs\` from \`src/data/concepts/*.json\` and
\`src/data/plays/*.json\`. Edit the data (\`football\`, \`sources\`, \`copy\`), not this file.

Standard: a curated, recognizable, internally consistent representation of each concept.
Where coaching systems differ, one presentation is chosen and the choice is written into the
concept's \`football\` block. Assumed defensive fronts are noted where blocking depends on
them; defenders are never drawn.

${plays.length} plays · ${groups.length} concepts · ${Object.keys(forms).length} formations
`;
let fam = null;
for (const list of groups) {
  const p = list[0];
  if (p.family !== fam) { fam = p.family; md += `\n## ${LABEL[fam] || fam}\n`; }
  md += `\n### ${p.name}\n\n`;
  md += `- **Presentations:** ${list.map((q) => `${forms[q.formation] ? forms[q.formation].name : q.formation} (${q.personnel}${q.side ? `, ${q.side}` : ''})`).join(' · ')}\n`;
  md += `- **Wallpaper:** ${p.copy.situation ? `${p.copy.situation} — ` : ''}"${p.copy.description}"\n`;
  const rel = Array.from(new Set((p.relationships || []).map((r) => r.type))).join(', ');
  if (rel) md += `- **Defining relationship:** ${rel}\n`;
  for (const [k, v] of Object.entries(p.football || {})) md += `- **${k[0].toUpperCase() + k.slice(1)}:** ${v}\n`;
  if (p.sources) md += `- **Sources:** ${p.sources.join('; ')}\n`;
}
mkdirSync(new URL('docs/football/', root), { recursive: true });
writeFileSync(new URL('docs/football/CONCEPTS.md', root), md);
console.log(`docs/football/CONCEPTS.md: ${plays.length} plays, ${groups.length} concepts`);
