// Regenerate docs/football/CONCEPTS.md from the play data (the data is the source of truth):
//   node tools/concepts-doc.mjs
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const root = new URL('../', import.meta.url);
const read = (p) => JSON.parse(readFileSync(new URL(p, root), 'utf8'));
const manifest = read('src/data/manifest.json');
const forms = Object.fromEntries(manifest.formations.map((f) => { const j = read(`src/data/${f}`); return [j.id, j]; }));
const plays = manifest.plays.map((p) => read(`src/data/${p}`));

const ORDER = ['dropback_pass', 'quick_pass', 'play_action', 'rpo', 'screen', 'run'];
const LABEL = { dropback_pass: 'Dropback pass', quick_pass: 'Quick game', play_action: 'Play-action', rpo: 'RPO', screen: 'Screens', run: 'Run game' };
plays.sort((a, b) => ORDER.indexOf(a.family) - ORDER.indexOf(b.family) || a.name.localeCompare(b.name));

let md = `# Football concept reference

Generated by \`node tools/concepts-doc.mjs\` from \`src/data/plays/*.json\`. Edit the play JSON
(\`football\`, \`sources\`, \`copy\`), not this file.

Standard: a curated, recognizable, internally consistent representation of each concept.
Where coaching systems differ, one presentation is chosen and the choice is written into the
play's \`football\` block. Assumed defensive fronts are noted where blocking depends on them;
defenders are never drawn.

${plays.length} plays · ${new Set(plays.map((p) => p.conceptId)).size} concepts · ${Object.keys(forms).length} formations
`;
let fam = null;
for (const p of plays) {
  if (p.family !== fam) { fam = p.family; md += `\n## ${LABEL[fam] || fam}\n`; }
  const f = forms[p.formation];
  md += `\n### ${p.name}\n\n`;
  md += `- **Play id:** \`${p.id}\` · **Formation:** ${f ? f.name : p.formation} (${p.personnel})${p.side ? ` · **Side:** ${p.side}` : ''}\n`;
  md += `- **Wallpaper:** ${p.copy.situation ? `${p.copy.situation} — ` : ''}"${p.copy.description}"\n`;
  const rel = (p.relationships || []).map((r) => r.type).join(', ');
  if (rel) md += `- **Defining relationship:** ${rel}\n`;
  for (const [k, v] of Object.entries(p.football || {})) md += `- **${k[0].toUpperCase() + k.slice(1)}:** ${v}\n`;
  if (p.reads && p.reads.length) md += `- **Reads:** ${p.reads.join(' → ')}\n`;
  if (p.sources) md += `- **Sources:** ${p.sources.join('; ')}\n`;
}
mkdirSync(new URL('docs/football/', root), { recursive: true });
writeFileSync(new URL('docs/football/CONCEPTS.md', root), md);
console.log(`docs/football/CONCEPTS.md: ${plays.length} plays`);
